### ISSUE TITLE
Could not find com.android.tools.build:gradle:3.4.1

### ISSUE THREAD

**Issue by jpage4500** [BrantApps/gradle-amazon-app-store-publisher#1]
Hi,

First of all - thanks for working on this! I was initially trying to write some python scripts to do this but never got it all finished. I use the Triple-T / gradle-play-publisher library and saw mention of this for Amazon.

I added the library but got a build error (below). Is there a way to ignore the build tools version?

```
Could not find com.android.tools.build:gradle:3.4.1.
Searched in the following locations:
  - https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.4.1/gradle-3.4.1.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :app > app.brant.amazonappstorepublisher:app.brant.amazonappstorepublisher.gradle.plugin:0.1.0 > app.brant:amazonappstorepublisher:0.1.0
Open File
```

Here's my top-level build.gradle file
```
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
```

**Comment by BrantApps** [comment]
For some reason, I never got a notification about this (checks settings 🤔)

I'll take a look. How do I replicate?

**Comment by BrantApps** [comment]
I think that this plugin generally had issues with 4.0.1. I've been struggling to upgrade AGP on my play project (where a lot of my research happens) but making progress again recently.

**Comment by jpage4500** [comment]
I just took another shot at implementing this library and got this to work. I was following the plugins section which looks like all of my other libraries I'm using.. but, switching to the 'legacy' section (below) fixed it.

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "app.brant:amazonappstorepublisher:0.1.0"
  }
}

apply plugin: "app.brant.amazonappstorepublisher"

```
